export const Type = {
    GET_QUESTIONS: "GET_QUESTIONS",
    GET_QUES_LOADING: 'GET_QUE_LOADING',
    GET_QUES_RECEIVED: 'GET_QUES_RECEIVED',
    GET_QUES_ERROR: 'GET_QUES_ERROR',
    SET_CURRENT_SCORE: 'SET_CURRENT_SCORE',
    SET_LAST_SCORE: 'SET_LAST_SCORE'
}